[package]
name = "tataku-client"
version = "0.5.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#  TODO: we should always assume gameplay and graphics here lol
[features]
default = [ "gameplay", "storyboards" ]
gameplay = [ "graphics", "bass_audio", "media_control", "ipc-channel" ]
bass_audio = [ "tataku-bass" ]
media_control = []
ui = []
storyboards = [ "tataku-game/storyboards" ]

# removes as much graphics-side stuff as possible
graphics = [ "winit", "ui", ]
dynamic_gamemodes = [ "tataku-game/dynamic_gamemodes" ]

texture_arrays = [ "tataku-wgpu/texture_arrays" ]
debug_sliders = [ "gamemode-osu/debug_sliders" ]

[dependencies]
tataku-common.workspace = true

tataku-game.workspace = true
tataku-wgpu.workspace = true
tataku-bass = { workspace = true, optional = true }

gamemode-osu.workspace = true
gamemode-taiko.workspace = true
gamemode-mania.workspace = true
gamemode-utyping.workspace = true


# framework stuff
tokio = { workspace = true, features = ["full"] }
ipc-channel = { workspace = true, optional = true }

# windowing
winit = { workspace = true, features = ["serde"], optional = true }

# serde
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

# logging
tracing.workspace = true
tracing-subscriber = { version =  "0.3.18", features = [ "chrono" ] }
tracing-appender = "0.2.3"
