[package]
name = "tataku-client"
version = "0.5.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = [ "storyboards", "bass_audio", "all_integrations" ]

# integrations
all_integrations = [ "discord", "lastfm", "media_controls" ]
discord = [ "integration-discord" ]
lastfm = [ "integration-lastfm" ]
media_controls = [ "integration-media-controls" ]
# ipc = [ "integration-ipc" ]

# audio
bass_audio = [ "tataku-bass" ]
kira_audio = [ "tataku-kira" ]


storyboards = [ "tataku-game/storyboards" ]
dynamic_gamemodes = [ "tataku-game/dynamic_gamemodes" ]

texture_arrays = [ "tataku-wgpu/texture_arrays" ]
debug_sliders = [ "gamemode-osu/debug_sliders" ]

[dependencies]
tataku-common.workspace = true
tataku-game.workspace = true
tataku-wgpu.workspace = true
tataku-bass = { workspace = true, optional = true }
tataku-kira = { workspace = true, optional = true }

# Gamemodes
gamemode-osu.workspace = true
gamemode-taiko.workspace = true
gamemode-mania.workspace = true
gamemode-utyping.workspace = true

# Integrations
integration-discord = { workspace = true, optional = true }
integration-lastfm = { workspace = true, optional = true }
integration-media-controls = { workspace = true, optional = true }



# framework stuff
tokio = { workspace = true, features = ["full"] }

# windowing
winit = { workspace = true, features = ["serde"] }

# serde
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

# logging
tracing.workspace = true
tracing-subscriber = { version =  "0.3.18", features = [ "chrono" ] }
tracing-appender = "0.2.3"
