[package]
name = "tataku-engine"
version = "0.5.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "gameplay" ]
gameplay = [ "graphics", "gilrs" ]
# kira_audio = ["rustfft", "uuid"]
debug_hitsounds = []
debug_perf_rating = []
debug_custom_menus = []

storyboards = []
texture_arrays = []
ui = [ "taffy", "mlua", "triple_buffer" ]

# removes as much graphics-side stuff as possible
graphics = [ "winit", "ui", "clipboard", "raw-window-handle", "fontdue", "image" ]

dynamic_gamemodes = [ "libloading" ]

[dependencies]
tataku-input.workspace = true
tataku-common.workspace = true
tataku-client-common.workspace = true
tataku-client-proc-macros.workspace = true

# framework stuff
lazy_static.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
async-trait.workspace = true

tokio = { workspace = true, features = [ "full" ] }
rusqlite = { workspace = true, features = [ "bundled" ] }
triple_buffer = { workspace = true, optional = true }

libloading = { workspace = true, optional = true }

# image stuff
image = { workspace = true, optional = true }
fontdue = { workspace = true, optional = true }

# windowing
winit = { workspace = true, features = ["serde"], optional = true }
raw-window-handle = { workspace = true, optional = true }
clipboard = { workspace = true, optional = true }

# gamepad input
gilrs = { workspace = true, features = ["serde-serialize"], optional = true }

# gui
taffy = { workspace = true, optional = true }

# networking
reqwest = { workspace = true, features = ["json"] }
native-tls.workspace = true
tokio-native-tls.workspace = true

# serde
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true

# decoding/encoding/zip stuff
zip.workspace = true
md5.workspace = true
lzma-rs.workspace = true
base64.workspace = true
encoding_rs.workspace = true
sha2.workspace = true


# other stuff
rand.workspace = true
fs_extra.workspace = true
mlua = { workspace = true, optional = true }


# logging
tracing.workspace = true
num-format.workspace = true
strfmt.workspace = true

# battery_level = { git = "https://gitlab.ayyeve.dev/ayyEve/battery-level-rs" }