[package]
name = "tataku-engine-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = [ "ui" ]
ui = [ "taffy" ]
debug_custom_menus = []

[dependencies]
tataku-common.workspace = true
tataku-client-proc-macros.workspace = true

taffy = { workspace = true, optional = true }
parking_lot.workspace = true
bitflags.workspace = true
tracing.workspace = true
strfmt.workspace = true

half.workspace = true
cgmath.workspace = true
serde.workspace = true
guillotiere.workspace = true
ureq.workspace = true
image.workspace = true
rand.workspace = true
num-format.workspace = true
paste.workspace = true
serde_json.workspace = true

md5.workspace = true
sha2.workspace = true
base64.workspace = true
