[package]
name = "tataku-client"
version = "0.5.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = [
    "storyboards",
    "bass_audio",
    # "kira_audio",
    "all_integrations",
    "graphics",
    # "dynamic_gamemodes"
]

# integrations
all_integrations = [ 
    "discord", 
    "lastfm", 
    # "media_controls" 
    # "ipc"
]
discord = [ "integration-discord" ]
lastfm = [ "integration-lastfm" ]
media_controls = [ "integration-media-controls" ]
# ipc = [ "integration-ipc" ]

# audio
bass_audio = [ "tataku-bass" ]
kira_audio = [ "tataku-kira" ]

storyboards = [ "tataku-game/storyboards" ]
dynamic_gamemodes = [ "tataku-game/dynamic_gamemodes" ]

texture_arrays = [ "tataku-wgpu/texture_arrays" ]
debug_sliders = [ "gamemode-osu/debug_sliders" ]

# helper for testing
graphics = [
    "tataku-game/graphics",
    "gamemode-osu/graphics",
    "gamemode-taiko/graphics",
    "gamemode-mania/graphics",
    "gamemode-utyping/graphics",
    "integration-lastfm/graphics",
    "integration-discord/graphics",
    "integration-media-controls/graphics",
    "tataku-wgpu",
    "gameplay"
]
gameplay = [
    "tataku-game/gameplay",
    "gamemode-osu/gameplay",
    "gamemode-taiko/gameplay",
    "gamemode-mania/gameplay",
    "gamemode-utyping/gameplay",
]

vello_rendering = [ "tataku-wgpu/vello_rendering" ]

[dependencies]
tataku-common.workspace = true
tataku-wgpu = { workspace = true, optional = true, features = ["graphics"] }
tataku-resources.workspace = true
tataku-bass = { workspace = true, optional = true }
tataku-kira = { workspace = true, optional = true }
tataku-game = { workspace = true }

# Gamemodes
gamemode-osu.workspace = true
gamemode-taiko.workspace = true
gamemode-mania.workspace = true
gamemode-utyping.workspace = true

# Integrations
integration-discord = { workspace = true, optional = true }
integration-lastfm = { workspace = true, optional = true }
integration-media-controls = { workspace = true, optional = true }



# framework stuff
tokio = { workspace = true, features = ["full"] }
clap = { version = "4.5", features = ["derive"] }

# windowing
winit = { workspace = true, features = ["serde"] }

# serde
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

# logging
tracing.workspace = true
tracing-subscriber = { version =  "0.3.18", features = [ "chrono" ] }
tracing-appender = "0.2.3"