<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/actions"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:actions="tataku/actions"
  xmlns:common="tataku/common"
  xmlns:input="tataku/input"
  xmlns:buildable-value="tataku/buildable-value"
  xmlns:text="tataku/text"
>

<xs:import namespace="tataku/buildable-value" schemaLocation="buildable_value.xsd"/>
<xs:import namespace="tataku/text" schemaLocation="text.xsd"/>
<xs:import namespace="tataku/common" schemaLocation="common.xsd"/>

<xs:group name="action-type">
  <xs:choice>
      <!-- none -->
      <xs:element name="none"/>

      <!-- internal -->
      <xs:element name="internal">
        <xs:complexType>
          <xs:attribute name="path" type="text:string" use="required"/>
        </xs:complexType>
      </xs:element>

      <!-- delayed -->
      <xs:element name="delayed">
        <xs:complexType>
          <xs:group ref="actions:action-type"/>
          <xs:attribute name="delay" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
      </xs:element>

      <!-- setMenu -->
      <xs:choice>
        <!-- value only -->
        <xs:element name="setMenu">
          <xs:annotation>
            <xs:documentation>Set the current menu to the provided ID</xs:documentation>
            <xs:documentation>Note!: Only one of @id or #content should be provided</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:group ref="buildable-value:buildableValue" minOccurs="0">
              <xs:annotation>
                <xs:documentation>The menu ID</xs:documentation>
              </xs:annotation>
            </xs:group>
            <xs:attribute name="id" type="xs:string">
              <xs:annotation>
                <xs:documentation>The menu ID</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>

        <!-- manually specified -->
        <xs:element name="setMenu">
          <xs:annotation>
            <xs:documentation>Set the current menu to the provided ID</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:all>
              <xs:element name="id" type="buildable-value:buildableValueElement" minOccurs="1">
                <xs:annotation>
                  <xs:documentation>The menu ID</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="inputs" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Input variables to pass to the menu</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="variable" type="actions:buildable-inputs" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:choice>

      <!-- addDialog -->
      <xs:choice>
        <!-- value only -->
        <xs:element name="addDialog">
          <xs:complexType>
            <xs:group ref="buildable-value:buildableValue" minOccurs="0"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="allow_duplicates" type="xs:boolean"/>
          </xs:complexType>

          <xs:key name="dialog_id">
            <xs:selector xpath="."/>
            <xs:field xpath="@id|*"/>
          </xs:key>
        </xs:element>

        <!-- manually specified -->
        <xs:element name="addDialog">
          <xs:complexType>
            <xs:all>
              <xs:element name="id" type="buildable-value:buildableValueElement"/>
              <xs:element name="inputs" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="variable" type="actions:buildable-inputs" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
            <xs:attribute name="allow_duplicates" type="xs:boolean"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>

      
      <xs:element name="custom">
        <xs:complexType>
          <xs:group ref="text:text" minOccurs="0" />
          <xs:attribute name="event" type="xs:string" />
        </xs:complexType>
      </xs:element>
      

      <xs:element name="closeDialog"/>

      <xs:element name="setValue">
        <xs:complexType>
          <xs:group ref="buildable-value:buildableValue" minOccurs="1"/>
          <xs:attribute name="key" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="map"> 
        <xs:complexType>
          <xs:group ref="actions:map-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="game">
        <xs:complexType>
          <xs:group ref="actions:game-action" minOccurs="1"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="mod">
        <xs:complexType>
          <xs:group ref="actions:mod-action"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="mods">
        <xs:complexType>
          <xs:group ref="actions:mod-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="song">
        <xs:complexType>
          <xs:group ref="actions:song-action"/>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="multiplayer">
        <xs:complexType>
          <xs:group ref="actions:multiplayer-action"/>
        </xs:complexType>
      </xs:element>


      <xs:element name="cursor">
        <xs:complexType>
          <xs:group ref="actions:cursor-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="chat">
        <xs:complexType>
          <xs:group ref="actions:chat-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="gameplay">
        <xs:complexType>
          <xs:group ref="actions:gameplay-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="onlineContent">
        <xs:complexType>
          <xs:group ref="actions:online-content-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="conditional">
        <xs:complexType>
          <xs:choice minOccurs="1">
            <xs:group ref="actions:action-cond-specified"/>
            <xs:group ref="actions:action-type"/>
          </xs:choice>
          <xs:attribute name="cond" type="common:condition" use="required"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="list">
        <xs:complexType>
            <xs:group ref="actions:action-type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:complexType>
      </xs:element>
      
  </xs:choice>
</xs:group>

<xs:complexType name="buildable-inputs">
  <xs:choice>
    <xs:group ref="buildable-value:buildableValue" />
    <xs:element name="value" type="buildable-value:buildableValueElement" />
  </xs:choice>
  <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>


<xs:group name="action-cond-specified">
  <xs:sequence>
    <xs:element name="true" minOccurs="1" maxOccurs="1">
      <xs:complexType>
        <xs:group ref="actions:action-type"/>
      </xs:complexType>
    </xs:element>

    <xs:element name="false" minOccurs="0" maxOccurs="1">
      <xs:complexType>
        <xs:group ref="actions:action-type"/>
      </xs:complexType>
    </xs:element>
  </xs:sequence>
</xs:group>



<!-- Map Actions -->
<xs:group name="map-action">
  <xs:choice>
      <xs:element name="play"/>
      <xs:element name="confirm"/>
      <xs:element name="next"/>
      <xs:element name="previous">
        <xs:complexType>
          <xs:group ref="actions:map-action-if-none" minOccurs="0" maxOccurs="1"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="random">  
        <xs:complexType>
          <xs:attribute name="use_preview" type="xs:boolean"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="selectGroup" type="buildable-value:buildableValueElement"/>
      <xs:element name="selectMap" type="buildable-value:buildableValueElement"/>
      <xs:element name="setPlaymode" type="buildable-value:buildableValueElement"/>

      <xs:element name="refreshMaps"/>
      <xs:element name="delete" type="buildable-value:buildableValueElement"/>
      <xs:element name="deleteCurrent"/>
      
      <xs:element name="nextMap"/>
      <xs:element name="nextSet"/>
      <xs:element name="previousMap"/>
      <xs:element name="previousSet"/>

  </xs:choice>
</xs:group>

<xs:group name="map-action-if-none">
  <xs:choice>
    <xs:element name="continueCurrent"/>
    <xs:element name="setNone"/>
    <xs:element name="random"> 
      <xs:complexType>
        <xs:attribute name="use_preview" type="xs:boolean"/>
      </xs:complexType>
    </xs:element>
  </xs:choice>
</xs:group>


<!-- Song Actions -->
<xs:group name="song-action">
  <xs:choice>
    <xs:element name="play"/>
    <xs:element name="pause"/>
    <xs:element name="toggle"/>
    <xs:element name="restart"/>
    <xs:element name="pushQueue"/>
    <xs:element name="popQueue"/>
    <xs:element name="seek" type="buildable-value:buildableValueElement"/>
    <xs:element name="position" type="buildable-value:buildableValueElement"/>
    <xs:element name="rate" type="buildable-value:buildableValueElement"/>
  </xs:choice>
</xs:group>


<!-- Gameplay Actions -->
<xs:group name="gameplay-action">
  <xs:choice>
    <xs:element name="resume"/>
    <xs:element name="pause"/>
    <xs:element name="quit"/>
    <xs:element name="retry"/>
  </xs:choice>
</xs:group>


<!-- Cursor Actions -->
<xs:group name="cursor-action">
  <xs:choice>
    <xs:element name="show"/>
    <xs:element name="hide"/>
  </xs:choice>
</xs:group>


<!-- Chat Actions -->
<xs:group name="chat-action">
  <xs:choice>
    <!-- send message -->
    <xs:element name="sendMessage">
      <xs:complexType>
        <xs:all>
          <xs:element name="channel" type="text:textElement"/>
          <xs:element name="message" type="text:textElement"/>
        </xs:all>
      </xs:complexType>
    </xs:element>
    
    <!-- open channel -->
    <xs:element name="openChannel">
      <xs:complexType>
        <xs:choice>
          <xs:group ref="text:text"/>
          <xs:element name="channel" type="text:textElement"/>
        </xs:choice>
      </xs:complexType>
    </xs:element>

    <!-- close channel -->
    <xs:element name="closeChannel">
      <xs:complexType>
        <xs:choice>
          <xs:group ref="text:text"/>
          <xs:element name="channel" type="text:textElement"/>
        </xs:choice>
      </xs:complexType>
    </xs:element>

  </xs:choice>
</xs:group>


<!-- Game Actions -->
<xs:group name="game-action">
  <xs:choice>
      <xs:element name="quit"/>
      <xs:element name="refreshScores"/>
      
      <xs:element name="viewScore" type="buildable-value:buildableValueElement"/>

      <xs:element name="notification">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="color" type="xs:string" minOccurs="0"/>
            <xs:element name="duration" minOccurs="1" maxOccurs="1"> 
              <xs:complexType mixed="true">
                <xs:group ref="buildable-value:buildableValue"/>
              </xs:complexType>
            </xs:element>

            <xs:element name="text" minOccurs="1" maxOccurs="1"> 
              <xs:complexType>
                <xs:group ref="text:text" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="color" type="xs:string"/>
        </xs:complexType>

        <xs:key name="notification-color">
          <xs:selector xpath="."/>
          <xs:field xpath="color|@color"/>
        </xs:key>
      </xs:element>

      <xs:element name="copyToClipboard">
        <xs:complexType>
          <xs:group ref="text:text"/>
        </xs:complexType>
      </xs:element>
  </xs:choice>
</xs:group>


<!-- Multiplayer Actions -->
<xs:group name="multiplayer-action">
  <xs:choice>
    <xs:element name="createLobby">
      <xs:complexType>
        <xs:all>
          <xs:element name="name" type="buildable-value:buildableValueElement" minOccurs="1" maxOccurs="1"/>
          <xs:element name="password" type="buildable-value:buildableValueElement" minOccurs="0" maxOccurs="1"/>
          <xs:element name="private" type="buildable-value:buildableValueElement" minOccurs="0" maxOccurs="1"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="joinLobby">
      <xs:complexType>
        <xs:choice>
          <xs:group ref="buildable-value:buildableValue"/>
          <xs:sequence>
            <xs:element name="lobby_id" type="buildable-value:buildableValueElement" minOccurs="1" maxOccurs="1"/>
            <xs:element name="password" type="buildable-value:buildableValueElement" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
        </xs:choice>
      </xs:complexType>
    </xs:element>

    <xs:element name="openMapLink"/>
    <xs:element name="startMatch"/>
    <xs:element name="ready"/>
    <xs:element name="unready"/>
    <xs:element name="leave"/>
    <xs:element name="quit"/>
    <xs:element name="start"/>
    
    <xs:element name="slot">
      <xs:complexType>
        <xs:group ref="actions:slot-action" minOccurs="1" maxOccurs="1"/>
      </xs:complexType>
    </xs:element>
    
  </xs:choice>
</xs:group>


<!-- Slot Actions -->
<xs:group name="slot-action">
  <xs:sequence>
    <xs:element name="slot" type="buildable-value:buildableValueElement"/>
    <xs:choice>
      <xs:group ref="actions:slot-action-type"/>
      <xs:element name="action">
        <xs:complexType>
          <xs:group ref="actions:slot-action-type"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:sequence>
</xs:group>

<xs:group name="slot-action-type">
  <xs:choice>
    <xs:element name="showProfile"/>
    <xs:element name="move"/>
    <xs:element name="transferHost"/>
    <xs:element name="lock"/>
    <xs:element name="unlock"/>
    <xs:element name="kick"/>
  </xs:choice>
</xs:group>


<!-- Mod Actions -->
<xs:group name="mod-action">
  <xs:choice>
      <xs:element name="addMod" type="buildable-value:buildableValueElement" minOccurs="1"/>
      <xs:element name="removeMod" type="buildable-value:buildableValueElement" minOccurs="1"/>
      <xs:element name="toggleMod" type="buildable-value:buildableValueElement" minOccurs="1"/>
      <xs:element name="setSpeed" type="buildable-value:buildableValueElement" minOccurs="1"/>
      <xs:element name="addSpeed" type="buildable-value:buildableValueElement" minOccurs="1"/>
  </xs:choice>
</xs:group>


<!-- Online Content Actions -->
<xs:group name="online-content-action">
  <xs:choice>
      <xs:element name="audioPreview" type="buildable-value:buildableValueElement" minOccurs="1"/>
      <xs:element name="download" type="buildable-value:buildableValueElement" minOccurs="1"/>
      <xs:element name="search" type="actions:online-content-action-search" minOccurs="1"/>

      <xs:element name="nextPage"/>
      <xs:element name="previousPage"/>
      <xs:element name="setPage" type="buildable-value:buildableValueElement" minOccurs="1"/>
  </xs:choice>
</xs:group>

<xs:complexType name="online-content-action-search">
  <xs:all>
    <xs:element name="engineId" type="buildable-value:buildableValueElement" minOccurs="1" />
    <xs:element name="searchType" type="buildable-value:buildableValueElement" minOccurs="1" />
    <xs:element name="page" type="buildable-value:buildableValueElement" minOccurs="1" />
    <xs:element name="query" type="buildable-value:buildableValueElement" />
    
    <!-- value list -->
    <xs:element name="values" minOccurs="0">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="entry" type="actions:search_value" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>

  </xs:all>
  <xs:attribute name="valuesKeyValuePath" type="text:string" />
  <xs:attribute name="valuesMapPath" type="text:string" />
</xs:complexType>


<xs:complexType name="search_value">
  <xs:all>
    <xs:element name="id" type="buildable-value:buildableValueElement" minOccurs="1" />
    <xs:element name="value" type="buildable-value:buildableValueElement" minOccurs="1" />
  </xs:all>
</xs:complexType>


</xs:schema>