<?xml version="1.0"?>
<xs:schema 
  xmlns:xs = "http://www.w3.org/2001/XMLSchema"
  xmlns:elements = "tataku/elements"
  xmlns:actions = "tataku/actions"
  xmlns:events = "tataku/events"
  xmlns:common = "tataku/common"
  xmlns:text = "tataku/text"
>

<!-- imports -->
<xs:import namespace="tataku/elements" schemaLocation="elements/elements.xsd"/>
<xs:import namespace="tataku/actions" schemaLocation="actions/actions.xsd"/>
<xs:import namespace="tataku/events" schemaLocation="events.xsd"/>
<xs:import namespace="tataku/common" schemaLocation="common.xsd"/>
<xs:import namespace="tataku/text" schemaLocation="text.xsd"/>


<!-- entry point definition -->
<xs:element name="dialog">
  <xs:complexType>
    <xs:all>
      <xs:element name="style" type="text:string" minOccurs="0"/>
      <xs:element name="inputs" type="common:input-variables" minOccurs="0"/>
      <xs:element name="events" type="common:event-list" minOccurs="0"/>

      <xs:element name="element">
        <xs:complexType>
          <xs:group ref="elements:element"/>
        </xs:complexType>
      </xs:element>
    </xs:all>
    
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="title" type="xs:string"/>
    <xs:attribute name="allow_multiple" type="xs:boolean"/>
    <xs:attribute name="draggable" type="xs:boolean"/>
    <xs:attribute name="resizable" type="xs:boolean"/>
  </xs:complexType>
</xs:element>

</xs:schema> 