<?xml version="1.0"?>
<xs:schema 
  xmlns:xs = "http://www.w3.org/2001/XMLSchema"
  xmlns:actions = "tataku/actions"
  xmlns:events = "tataku/events"
  xmlns:elements = "tataku/elements"
  xmlns:common = "tataku/common"
  xmlns:text = "tataku/text"
>

<!-- imports -->
<xs:import namespace="tataku/elements" schemaLocation="elements/elements.xsd"/>
<xs:import namespace="tataku/actions" schemaLocation="actions/actions.xsd"/>
<xs:import namespace="tataku/events" schemaLocation="events.xsd"/>
<xs:import namespace="tataku/common" schemaLocation="common.xsd"/>
<xs:import namespace="tataku/text" schemaLocation="text.xsd"/>


<!-- entry point definition -->
<xs:element name="menu">
  <xs:complexType>
    <!-- todo: replace with xs:all for xml v1.1 -->
    <xs:sequence>
      <xs:element name="style" type="text:string" minOccurs="0"/>
      <xs:element name="events" type="common:event-list" minOccurs="0"/>
      <xs:element name="inputs" type="common:input-variables" minOccurs="0"/>

      <xs:group ref="elements:element"/>
    </xs:sequence>

    <xs:attribute name="id" type="text:string" use="required"/>
  </xs:complexType>
</xs:element>


</xs:schema>
