<?xml version="1.0"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:text="tataku/text"
    targetNamespace="tataku/text"
>

<xs:complexType name="text" mixed="true">
    <xs:group ref="text:text-wrapped" />
</xs:complexType>

<xs:simpleType name="string">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="collapse"/>
    </xs:restriction>
</xs:simpleType>

<xs:group name="text-wrapped">
    <xs:choice>
        <xs:element name="locale" type="text:string"/>
        <xs:element name="variable" type="text:string"/>

        <xs:element name="display">
            <xs:complexType mixed="true">
                <xs:attribute name="precision" type="xs:long"/>
            </xs:complexType>
        </xs:element>

        <xs:element name="calc" type="text:string"/>

        <xs:element name="iter">
            <xs:complexType>
                <xs:attribute name="variable" type="text:string" use="required"/>
                <xs:attribute name="property" type="text:string"/>
                <xs:attribute name="join" type="text:string" use="required"/>
            </xs:complexType>
        </xs:element>
    </xs:choice>
</xs:group>

</xs:schema>
