stages:
  - build-client
  - release

build-windows-linux:
  stage: build-client
  image: ayyeve/tataku-client-build:latest
  rules:
    # - if: $TATAKU_RELEASE_KEY != null
    # - if: $CI_COMMIT_REF_PROTECTED != "true"
    #   when: never
  script:
    # linux
    # build
    - ~/.cargo/bin/cargo mommy build --release
    # push
    - curl -X PUT http://$RELEASE_ADDR/$CI_COMMIT_BRANCH/linux/tataku-client --upload-file $CI_PROJECT_DIR/target/release/tataku-client
    
    # windows 
    # build
    - ~/.cargo/bin/cargo mommy build --release --target x86_64-pc-windows-gnu
    # push 
    - curl -X PUT http://$RELEASE_ADDR/$CI_COMMIT_BRANCH/windows/tataku-client.exe --upload-file $CI_PROJECT_DIR/target/x86_64-pc-windows-gnu/release/tataku-client.exe
  tags:
    - docker
    - linux

# build-windows:
#   stage: build-client
#   image: 
#   script:
#     - cargo build --release
#     - cp ./target/release/tataku-client.exe //192.168.0.170/website/cdn/tataku/releases/windows/tataku-client.exe
#   tags:
#     - windows
#     - local

# # TODO: build-mac
# build-mac:
#   stage: build-client
#   image: rust:latest
#   rules:
#     - if: $TATAKU_RELEASE_KEY != null
#       when: never
#   script:
#     - cargo build --release --verbose
#     - ./release/linux.sh
#   tags:
#     - mac
#     - local

releases:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_REF_PROTECTED # Run this job when commits are pushed or merged to a protected branch
  script:
    - echo "Creating release"
  release:
    tag_name: '$CI_COMMIT_REF_PROTECTED-$CI_COMMIT_TIMESTAMP'
    description: 'Automatic $CI_COMMIT_BRANCH release'
    ref: '$CI_COMMIT_SHA'
