stages:
  - build-client
  - release

build-linux:
  stage: build-client
  image: ayyeve/tataku-client-build:latest
  script:
    - ~/.cargo/bin/cargo mommy build --release
  after_script:
    - echo "LINUX_JOB=$CI_JOB_URL" >> job.env
  tags:
    - docker
    - linux
  artifacts:
    paths:
      - target/release/tataku-client
    reports:
      dotenv: job.env

build-windows:
  stage: build-client
  image: ayyeve/tataku-client-build:latest
  script:
    # Cross-compiled from linux
    - ~/.cargo/bin/cargo mommy build --release --target x86_64-pc-windows-gnu
  after_script:
    - echo "WINDOWS_JOB=$CI_JOB_URL" >> job.env
  tags:
    - docker
    - linux
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/tataku-client.exe
    reports:
      dotenv: job.env

# # TODO: build-mac
# build-mac:
#   stage: build-client
#   image: rust:latest
#   rules:
#     - if: $TATAKU_RELEASE_KEY != null
#       when: never
#   script:
#     - cargo build --release --verbose
#     - ./release/linux.sh
#   tags:
#     - mac
#     - local

prepare-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_MERGE_REQUEST_ID
      when: never # Do not run this job for merge requests
    - if: $CI_COMMIT_REF_PROTECTED # Run this job when commits are pushed or merged to a protected branch
  script:
    - echo DATETIME='$(git show -s --format="%cd" --date=format:"%Y%m%d%H%M")' >> vars.env
  artifacts:
    reports:
      dotenv: vars.env

releases:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_MERGE_REQUEST_ID
      when: never # Do not run this job for merge requests
    - if: $CI_COMMIT_REF_PROTECTED # Run this job when commits are pushed or merged to a protected branch
  needs:
    - job: prepare-release
      artifacts: true
    - job: build-linux
      artifacts: true
    - job: build-windows
      artifacts: true
  script:
    - echo Removing old tag and release
    - git push origin :refs/tags/$CI_COMMIT_BRANCH || ignore=$?
    - echo Creating release $CI_COMMIT_BRANCH-$DATETIME
  release:
    tag_name: $CI_COMMIT_BRANCH
    description: 'Automatic $CI_COMMIT_BRANCH release'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: Linux x86_64
          url: $LINUX_JOB/artifacts/file/target/release/tataku-client
        - name: Windows x86_64
          url: $WINDOWS_JOB/artifacts/file/target/x86_64-pc-windows-gnu/release/tataku-client.exe
