stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - apt update
    - apt install libasound2-dev cmake -y
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true