[workspace.package]
authors = [
    "Eve <hi.its.eve@gmail.com>",
    "~Nebula~ <stefanb1289@gmail.com>"
]
edition = "2024"
rust-version = "1.89"

[workspace]
members = [
    # engine
    "crates/engine/extra/*",
    "crates/engine/audio/*",
    "crates/engine/renderers/*",
    "crates/engine/tataku-engine",
    "crates/engine/tataku-input",
    "crates/engine/tataku-graphics",
    "crates/engine/tataku-ui",

    # game
    "crates/game/proc_macros",
    "crates/game/tataku-client",
    "crates/game/tataku-game",
    "crates/game/tataku-interface",
    "crates/game/windows/*",


    "crates/gamemodes/*" ,
    "crates/integrations/*",
    "crates/resources/*",

    "crates/databases/*", 
]
default-members = [ "crates/game/tataku-client" ]
resolver = "2"

[workspace.lints]
clippy.new_without_default = "allow"
clippy.too_many_arguments = "allow"
clippy.module_inception = "allow"
clippy.type_complexity = "allow"
clippy.todo = "warn"

clippy.bool_to_int_with_if = "warn"
clippy.cloned_instead_of_copied = "warn"
clippy.comparison_chain = "warn"
clippy.default_trait_access = "warn"
clippy.filter_map_next = "warn"
clippy.format_collect = "warn"
clippy.implicit_clone = "warn"
clippy.inefficient_to_string = "warn"
clippy.map_unwrap_or = "warn"
clippy.match_wild_err_arm = "warn"
clippy.needless_continue = "warn"
clippy.needless_for_each = "warn"
clippy.needless_pass_by_value = "warn"
clippy.option_option = "warn"
clippy.option_as_ref_cloned = "deny"
clippy.ref_option = "warn"
clippy.semicolon_if_nothing_returned = "warn"

rust.unused_must_use = "deny"

[workspace.dependencies]
# tataku-common = { version = "0.20.1", registry = "tataku-registry", path = "../tataku-common/tataku-common" }
tataku-common = { version = "0.21.0", registry = "tataku-registry" }

# bulk engine imports
tataku-client-proc-macros.path = "crates/game/proc_macros"
tataku-ui.path = "crates/engine/tataku-ui"
tataku-input.path = "crates/engine/tataku-input"
tataku-engine.path = "crates/engine/tataku-engine"
tataku-graphics.path = "crates/engine/tataku-graphics"
tataku-engine-common.path = "crates/engine/engine-common"
# bulk engine extra imports
shunting-yard.path = "crates/engine/extra/shunting-yard"
path-shunting-yard.path = "crates/engine/extra/path-shunting-yard"
buildable-shunting-yard.path = "crates/engine/extra/buildable-shunting-yard"

#  bulk game imports
tataku-game.path = "crates/game/tataku-game"
tataku-client.path = "crates/game/tataku-client"
tataku-interface.path = "crates/game/tataku-interface"
tataku-resources.path = "crates/resources/tataku-resources"

# Audio
tataku-audio.path = "crates/engine/audio/audio-common"
tataku-bass.path = "crates/engine/audio/tataku-bass"
tataku-kira.path = "crates/engine/audio/tataku-kira"
tataku-null-audio.path = "crates/engine/audio/null-audio"

# Renderers
tataku-wgpu.path = "crates/engine/renderers/tataku-wgpu"
tataku-null-renderer.path = "crates/engine/renderers/null-renderer"

# Windows
tataku-winit.path = "crates/game/windows/tataku-winit"

# Gamemodes
gamemode-osu.path = "crates/gamemodes/osu"
gamemode-taiko.path = "crates/gamemodes/taiko"
gamemode-mania.path = "crates/gamemodes/mania"
gamemode-utyping.path = "crates/gamemodes/utyping"

# Integrations
integration-discord.path = "crates/integrations/discord"
integration-lastfm.path = "crates/integrations/lastfm"
integration-media-controls.path = "crates/integrations/media_controls"

# databases
tataku-sqlite.path = "crates/databases/tataku-sqlite"
tataku-redb.path = "crates/databases/tataku-redb"

# framework stuff
lazy_static = "1.5.0"
parking_lot = "0.12.3"
tokio = { version = "1.44.2", features = [ "full" ] }
rusqlite = { version = "0.37.0", features = [ "bundled" ] }
futures-util = { version = "0.3.31", features = [ "async-await", "sink", "std" ] }
async-trait = "0.1.87"
async-recursion = "1.1.1"
triple_buffer = "8.1.0"
crossbeam = "0.8.4"
bitflags = "2.9"
notify = "8.2.0"
smol_str = "*"

libloading = "0.8.6"

# image stuff
image = { version = "0.25.5", default-features = false, features = [ "png", "jpeg", "gif" ] }
parley = "0.5.0"
swash = "0.2.5"

# math stuff
cgmath = "0.18.0"
guillotiere = "0.6.2"
lyon_tessellation = "1.0.15"
half = "2.6"

# graphics
bytemuck = { version = "1.21.0", features = [ "derive" ] }
raw-window-handle = "0.6.2"
clipboard = "0.5.0"
wgpu = "26.0.1"
winit = "0.30.12"

# gamepad input
gilrs = { version = "0.11.0", features = [ "serde-serialize" ] }

# gui
taffy = { version = "0.9", features = [ "serde" ] }
slotmap = "1.0.7"

# taffy = { version = "0.8.3", features = [ "serde" ], git="https://github.com/DioxusLabs/taffy.git", branch="units" }
simplecss = { version = "0.2.2", git = "https://github.com/ayyEve/simplecss.git", features = ["at_rules"] }
quick-xml = { version = "0.38.3", features = [ "serialize" ]}

# networking
rustls = { version = "0.23.26", default-features = false }
native-tls = "0.2.14"
tokio-native-tls = "0.3.1"
tokio-tungstenite = { version = "0.27", features = [ "rustls-tls-native-roots" ] }
# reqwest = { version = "0.12.15", features = [ "json", "blocking" ] }
rustls-graviola = "0.3.0"
ureq = "3.1.4"


# serde
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"

# decoding/encoding/zip stuff
sha2 = "0.10.8"
zip = { version = "2.2.3", default-features = false, features = [ "deflate", "deflate64", "bzip2" ] }
md5 = "0.8.0"
lzma-rs = "0.3.0"
base64 = "0.22.1"
encoding_rs = { version = "0.8.35" }


# other stuff
rand = "0.9.0"
chrono = "0.4.39"
fs_extra = "1.3.0"
cacache = "13.1.0"
uuid = { version = "1.11.0", features = [ "v4" ] }
paste = "1.0"


# logging
tracing = "0.1.41"
num-format = "0.4.4"
strfmt = "0.2.4"

# battery_level = { git = "https://gitlab.ayyeve.dev/ayyEve/battery-level-rs" }

[profile.dev]
opt-level = 3
