[package]
name = "tataku-client"
version = "0.1.0"
authors = [
    "Eve <hi.its.eve@gmail.com>",
    "~Nebula~ <stefanb1289@gmail.com>"
]
edition = "2021"
build = "build/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bass_audio", "discord"]
bass_audio = ["bass-rs"]
neb_audio = ["cpal", "symphonia", "rustfft", "uuid"]
discord = ["discord-rich-presence"]
debug_sliders = []
debug_hitsounds = []
snipping = []

[dependencies]
tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
# tataku-common = { path = "C:/Users/Eve/Desktop/Projects/rust/tataku/tataku-common" }

# framework stuff
lazy_static = "1.4"
parking_lot = "0.12"
tokio = { version = "1.16", features = ["full"] }
rusqlite = { version = "0.27", features = ["bundled"] }
futures-util = { version = "0.3", features = ["async-await", "sink", "std"] }
async-trait = "0.1"
rayon = "1.5.1"
bombs = "0.1.5"
triple_buffer = "6.0"

# gl/piston etc
# careful when verison bumping these
gl = "0.13"
glfw = { version = "0.43.0", features = ["image"] }
image = "0.23"
piston = "0.53.0"
lyon_tessellation = "0.17"

pistoncore-glfw_window = { version = "0.74" }
ayyeve-piston-ui = { version = "0.5.3", registry = "tataku" }
# ayyeve-piston-ui = {path="C:/Users/Eve/Desktop/Projects/rust/tataku/ayyeve-piston-ui"}
piston2d-graphics = { version = "0.41.0", registry = "tataku" }
piston2d-opengl_graphics = { version = "0.79.1", registry = "tataku" }
fontdue = "0.7"



# bass audio
bass-rs = { version="0.1", optional = true }

# neb audio
cpal = { version = "0.13.3", optional = true }
symphonia = { version = "0.3.0", default-features = false, features = ["mp3", "ogg", "wav", "pcm"], optional = true }
rustfft = { version = "6.0", optional = true }
uuid = { version = "0.8", features = ["v4"], optional = true }

# networking
sha2 = "0.10"
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
discord-rich-presence = { version = "0.2.0", optional = true }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

# helpers
zip = "0.5"
md5 = "0.7.0"
rand = "0.8.4"
encoding_rs = "0.8"
chrono = "0.4"
lzma-rs = "0.2"
png = "*"
base64 = "*"
fs_extra = "1.2.0"

# logging
tataku-logging = { git = "https://gitlab.ayyeve.xyz/tataku/tataku-logging" }
log = "0.4.16"

# battery_level = { git = "https://gitlab.ayyeve.xyz/ayyEve/battery-level-rs" }


[build-dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
# tataku-common = { path = "C:/Users/Eve/Desktop/Projects/rust/tataku/tataku-common" }


[package.metadata.x]
run = "cargo run --release"
run-neb = "cargo run --release --no-default-features --features neb_audio --features discord"

check = "cargo check --release"
check-neb = "cargo check --release --no-default-features --features neb_audio --features discord"
