[package]
name = "tataku-client"
version = "0.1.0"
authors = [
    "Eve <hi.its.eve@gmail.com>",
    "~Nebula~ <stefanb1289@gmail.com>"
]
edition = "2021"
build = "build/mod.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["gameplay"]
as_crate = ["no_media_control"]
gameplay = ["bass_audio", "graphics"]
bass_audio = ["bass-rs"]
# kira_audio = ["rustfft", "uuid"]
debug_sliders = []
debug_hitsounds = []
debug_perf_rating = []
debug_custom_menus = []
load_internal_menus_from_file = [] # whether to load builtin menus at runtime (if off, they're compiled into the game)

storyboards = []
texture_arrays = []
no_media_control = []
# removes as much graphics-side stuff as possible
graphics = ["wgpu", "bytemuck", "lyon_tessellation"]

[dependencies]
tataku-common = { version = "0.10.2", registry = "tataku-registry" }
# tataku-common = { path="../tataku-common" }
tataku-client-proc-macros = { path = "./proc_macros" }

# framework stuff
lazy_static = "1.4.0"
parking_lot = "0.12.3"
tokio = { version = "1.37.0", features = ["full"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
futures-util = { version = "0.3.30", features = ["async-await", "sink", "std"] }
async-trait = "0.1.80"
async-recursion = "1.1.1"
triple_buffer = "7.0.0"
crossbeam = "0.8.4"
global_value_manager = "0.1.1"

# image stuff
png = "0.17.13"
image = "0.25.1"
fontdue = "0.9.0"

# math stuff
cgmath = "0.18.0"
guillotiere = "0.6.2"
lyon_tessellation = { version="1.0.15", optional = true }

# windowing
wgpu = { version="0.20.1", optional = true }
bytemuck = { version = "1.16.0", features = [ "derive" ], optional = true }
winit = { version = "0.30.2", features = ["serde"] }
raw-window-handle = "0.6.2"
clipboard = "0.5.0"

# gamepad input
gilrs = { version = "0.10.7", features = ["serde-serialize"] }
# media controls
souvlaki = { version = "0.6", default-features = false, features = ["use_zbus"], git = "https://github.com/ayyEve/souvlaki.git" }

# gui
iced = { git = "https://github.com/iced-rs/iced.git", branch = "wgpu-0.20", features = ["canvas", "tokio", "debug", "image", "advanced", "lazy", "wgpu"], default-features = false }
iced_runtime = { git = "https://github.com/iced-rs/iced.git", branch = "wgpu-0.20" }
iced_winit = { git = "https://github.com/iced-rs/iced.git", branch = "wgpu-0.20" }

# bass audio
bass-rs = { version="0.2.3", optional = true }

# other audio
# kira = "0.7"
# rustfft = { version = "6.0", optional = true }

# networking
sha2 = "0.10.8"
tokio-tungstenite = { version = "0.22.0", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.12.4", features = ["json"] }
discord-rich-presence = "0.2.4"

# serde
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"

# decoding/encoding/zip stuff
zip = "2.1.1"
md5 = "0.7.0"
lzma-rs = "0.3.0"
base64 = "0.22.1"
encoding_rs = "0.8.34"

native-tls = "0.2.12"
tokio-native-tls = "0.3.1"

# other stuff
rand = "0.8.5"
chrono = "0.4.38"
fs_extra = "1.3.0"
uuid = { version = "1.8.0", features = ["v4"] }
rlua = "0.20.0"


# logging
tataku-logging = { git = "https://gitlab.ayyeve.dev/tataku/tataku-logging" }
log = "0.4.16"
num-format = "0.4.4"
strfmt = "0.2.4"

# battery_level = { git = "https://gitlab.ayyeve.dev/ayyEve/battery-level-rs" }


[build-dependencies]
tataku-common = { version = "0.10.2", registry = "tataku-registry" }