[package]
name = "tataku-client"
version = "0.1.0"
authors = [
    "Eve <hi.its.eve@gmail.com>",
    "~Nebula~ <stefanb1289@gmail.com>"
]
edition = "2021"
build = "build/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["glfw_window"]
# default = ["glfw_window", "winit"]
default = ["bass_audio", "discord", "snipping"]
bass_audio = ["bass-rs"]
# kira_audio = ["rustfft", "uuid"]
discord = ["discord-rich-presence"]
debug_sliders = []
debug_hitsounds = []
snipping = []
debug_perf_rating = []
log_frametimes = []
storyboards = []

# glfw_window = ["pistoncore-glfw_window", "bass_audio", "discord", "snipping", "glfw"]
# glutin_window = ["pistoncore-glutin_window", "bass_audio", "discord", "snipping", "winit"]

[dependencies]
tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
tataku-client-proc-macros = { path = "./proc_macros" }
# tataku-common = { path = "C:/Users/Eve/Desktop/Projects/rust/tataku/tataku-common" }

# framework stuff
lazy_static = "1.4"
parking_lot = "0.12"
tokio = { version = "1.16", features = ["full"] }
rusqlite = { version = "0.27", features = ["bundled"] }
futures-util = { version = "0.3", features = ["async-await", "sink", "std"] }
async-trait = "0.1"
bombs = "0.1.5"
triple_buffer = "6.0"
crossbeam = "*"
global_value_manager = "*"

# gl/piston etc
# careful when verison bumping these
# gl = "0.13"
image = "*"

# glfw = { version = "0.47", features = ["image"], optional = true }
# pistoncore-glfw_window = { version = "0.77", optional=true }


# pistoncore-glutin_window = { version = "0.70.1", optional=true }

# pistoncore-input = "*"


# ayyeve-piston-ui = "0.7"
fontdue = "0.7"
rectangle-pack = "0.4"
lyon_tessellation = "*"


wgpu = "*"
raw-window-handle = "0.5"
bytemuck = { version = "1.12", features = [ "derive" ] }
cgmath = "*"
winit = {version = "0.27", features = ["serde"]}

# bass audio
bass-rs = { version="0.2", optional = true }

# other audio audio
# kira = "0.7"
# rustfft = { version = "6.0", optional = true }
# uuid = { version = "0.8", features = ["v4"], optional = true }

# networking
sha2 = "0.10"
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
discord-rich-presence = { version = "0.2.0", optional = true }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

# helpers
zip = "0.5"
md5 = "0.7.0"
rand = "0.8.4"
encoding_rs = "0.8"
chrono = "0.4"
lzma-rs = "0.2"
png = "*"
base64 = "*"
fs_extra = "1.2.0"
deepsize = { version = "*"}
radix_fmt = "1"
clipboard = "0.5"


# logging
tataku-logging = { git = "https://gitlab.ayyeve.xyz/tataku/tataku-logging" }
log = "0.4.16"

# battery_level = { git = "https://gitlab.ayyeve.xyz/ayyEve/battery-level-rs" }


[build-dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
# tataku-common = { path = "C:/Users/Eve/Desktop/Projects/rust/tataku/tataku-common" }


[package.metadata.x]
run = "cargo run --release"
run-neb = "cargo run --release --no-default-features --features neb_audio --features discord"

check = "cargo check --release"
check-neb = "cargo check --release --no-default-features --features neb_audio --features discord"
