[package]
name = "tataku-client"
version = "0.1.0"
authors = [
    "Eve <hi.its.eve@gmail.com>",
    "~Nebula~ <stefanb1289@gmail.com>"
]
edition = "2021"
build = "build/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bass_audio", "discord"]
bass_audio = ["bass-rs"]
# kira_audio = ["rustfft", "uuid"]
discord = ["discord-rich-presence"]
debug_sliders = []
debug_hitsounds = []
debug_perf_rating = []
storyboards = []

[dependencies]
tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
tataku-client-proc-macros = { path = "./proc_macros" }

# framework stuff
lazy_static = "1.4"
parking_lot = "0.12"
tokio = { version = "1.16", features = ["full"] }
rusqlite = { version = "0.27", features = ["bundled"] }
futures-util = { version = "0.3", features = ["async-await", "sink", "std"] }
async-trait = "0.1"
bombs = "0.1.5"
triple_buffer = "6.0"
crossbeam = "*"
global_value_manager = "*"

# image stuff
png = "*"
image = "*"
fontdue = "0.7"

# math stuff
cgmath = "*"
guillotiere = "*"
lyon_tessellation = "*"

# windowing
wgpu = "*"
bytemuck = { version = "1.12", features = [ "derive" ] }
winit = { version = "0.27", features = ["serde"] }
clipboard = "0.5"
# gamepad input
gilrs = { version = "0.10", features = ["serde-serialize"] }

# bass audio
bass-rs = { version="0.2", optional = true }

# other audio
# kira = "0.7"
# rustfft = { version = "6.0", optional = true }
# uuid = { version = "0.8", features = ["v4"], optional = true }

# networking
sha2 = "0.10"
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
discord-rich-presence = { version = "0.2.0", optional = true }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

# decoding/encoding/zip stuff
zip = "0.5"
md5 = "0.7.0"
lzma-rs = "0.2"
base64 = "*"
encoding_rs = "0.8"

# other stuff
rand = "0.8.4"
chrono = "0.4"
fs_extra = "1.2.0"


# logging
tataku-logging = { git = "https://gitlab.ayyeve.xyz/tataku/tataku-logging" }
log = "0.4.16"

# battery_level = { git = "https://gitlab.ayyeve.xyz/ayyEve/battery-level-rs" }


[build-dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }