[package]
name = "tataku-client"
version = "0.1.0"
authors = ["Eve <hi.its.eve@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bass_audio"]
bass_audio = ["bass-rs"]
neb_audio = ["cpal", "symphonia", "rustfft", "uuid"]
discord = ["rustcord"]
debug_sliders = []
debug_hitsounds = []

[dependencies]
tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }

# framework stuff
lazy_static = "1.4"
parking_lot = "0.12"
tokio = { version = "1.16", features = ["full"] }
rusqlite = { version = "0.26", features = ["bundled"] }
futures-util = { version = "0.3", features = ["async-await", "sink", "std"] }

# gl/piston etc
# careful when updating these
gl = "0.13"
glfw = { version = "0.42.0", features = ["image"] }
image = "0.23"
piston = "0.53.0"
# piston2d-graphics = "0.40.0"
# piston2d-opengl_graphics = "0.78.0"

pistoncore-glfw_window = { git = "https://github.com/ayyEve/glfw_window" }

piston2d-opengl_graphics = { git = "https://github.com/ayyEve/opengl_graphics" }
piston2d-graphics = { git = "https://github.com/ayyEve/graphics" }
ayyeve-piston-ui = { git = "https://gitlab.ayyeve.xyz/ayyEve/ayyeve-piston-ui" }

# bass audio
bass-rs = { version="0.1", optional = true }

# neb audio
cpal = { version = "0.13.3", optional = true }
symphonia = { version = "0.3.0", default-features = false, features = ["mp3", "ogg", "wav", "pcm"], optional = true }
rustfft = { version = "6.0", optional = true }
uuid = { version = "0.8", features = ["v4"], optional = true }

# networking
sha2 = "0.10"
tokio-tungstenite = {version = "0.16.0", features = ["rustls-tls-native-roots"]}
reqwest = { version = "0.11.4", features = ["blocking"] }
rustcord = { git = "https://github.com/ayyEve/rustcord", optional=true }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

# helpers
zip = "0.5"
md5 = "0.7.0"
rand = "0.8.4"

# battery_level = { git = "https://gitlab.ayyeve.xyz/ayyEve/battery-level-rs" }


[build-dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
