[package]
name = "tataku-client"
version = "0.1.0"
authors = [
    "Eve <hi.its.eve@gmail.com>",
    "~Nebula~ <stefanb1289@gmail.com>"
]
edition = "2021"
build = "build/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["desktop"]
bass_audio = ["bass-rs"]
# kira_audio = ["rustfft", "uuid"]
discord = ["discord-rich-presence"]
debug_sliders = []
debug_hitsounds = []
snipping = []
debug_perf_rating = []
log_frametimes = []

desktop = ["pistoncore-glfw_window", "bass_audio", "discord", "snipping"]
mobile = ["pistoncore-glutin_window", "bass_audio", "discord"]

[dependencies]
tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
tataku-client-proc-macros = { path = "./proc_macros" }
# tataku-common = { path = "C:/Users/Eve/Desktop/Projects/rust/tataku/tataku-common" }

# framework stuff
lazy_static = "1.4"
parking_lot = "0.12"
tokio = { version = "1.16", features = ["full"] }
rusqlite = { version = "0.27", features = ["bundled"] }
futures-util = { version = "0.3", features = ["async-await", "sink", "std"] }
async-trait = "0.1"
bombs = "0.1.5"
triple_buffer = "6.0"
crossbeam = "*"

# gl/piston etc
# careful when verison bumping these
gl = "0.13"
glfw = { version = "0.47", features = ["image"] }
image = "*"


pistoncore-glutin_window = { version = "0.70.1", optional=true}
pistoncore-glfw_window = { version = "0.77", optional=true }

ayyeve-piston-ui = { version = "0.7", registry = "tataku" }
# ayyeve-piston-ui = {path="C:/Users/Eve/Desktop/Projects/rust/tataku/ayyeve-piston-ui"}
# piston2d-graphics = { version = "0.41.0", registry = "tataku" }
# piston2d-opengl_graphics = { version = "0.79.1", registry = "tataku" }
fontdue = "0.7"
rectangle-pack = "0.4"



# bass audio
bass-rs = { version="0.2", optional = true }

# other audio audio
# kira = "0.7"
# rustfft = { version = "6.0", optional = true }
# uuid = { version = "0.8", features = ["v4"], optional = true }

# networking
sha2 = "0.10"
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
discord-rich-presence = { version = "0.2.0", optional = true }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

# helpers
zip = "0.5"
md5 = "0.7.0"
rand = "0.8.4"
encoding_rs = "0.8"
chrono = "0.4"
lzma-rs = "0.2"
png = "*"
base64 = "*"
fs_extra = "1.2.0"

# logging
tataku-logging = { git = "https://gitlab.ayyeve.xyz/tataku/tataku-logging" }
log = "0.4.16"

# battery_level = { git = "https://gitlab.ayyeve.xyz/ayyEve/battery-level-rs" }


[build-dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

tataku-common = { git="https://gitlab.ayyeve.xyz/tataku/tataku-common" }
# tataku-common = { path = "C:/Users/Eve/Desktop/Projects/rust/tataku/tataku-common" }


[package.metadata.x]
run = "cargo run --release"
run-neb = "cargo run --release --no-default-features --features neb_audio --features discord"

check = "cargo check --release"
check-neb = "cargo check --release --no-default-features --features neb_audio --features discord"
