[package]
name = "tataku-interface"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
default = [
    # "debug_custom_menus"
]
debug_custom_menus = [ "tataku-client-common/debug_custom_menus" ]
graphics = [
    "tataku-engine/graphics"
]

[lints]
workspace = true


[dependencies]
tataku-ui.workspace = true
tataku-graphics.workspace = true
tataku-client-common = { workspace = true, optional = true }
tataku-engine = { workspace = true }

taffy.workspace = true
parley.workspace = true
# async-recursion.workspace = true

chrono.workspace = true
serde.workspace = true
simplecss.workspace = true
quick-xml.workspace = true
half.workspace = true

# [dev-dependencies]
# tataku-resources.workspace = true
