<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/actions"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:actions="tataku/actions"
  xmlns:common="tataku/common"
  xmlns:buildable-value="tataku/buildable-value"
  xmlns:text="tataku/text"


  xmlns:chat-actions="tataku/actions/chat"
  xmlns:cursor-actions="tataku/actions/cursor"
  xmlns:game-actions="tataku/actions/game"
  xmlns:gameplay-actions="tataku/actions/gameplay"
  xmlns:map-actions="tataku/actions/map"
  xmlns:mod-actions="tataku/actions/mod"
  xmlns:multiplayer-actions="tataku/actions/multiplayer"
  xmlns:online-content-actions="tataku/actions/online-content"
  xmlns:slot-actions="tataku/actions/slot"
  xmlns:song-actions="tataku/actions/song"
  xmlns:ui-actions="tataku/actions/ui"
>

<xs:import namespace="tataku/buildable-value" schemaLocation="../buildable_value.xsd"/>
<xs:import namespace="tataku/text" schemaLocation="../text.xsd"/>
<xs:import namespace="tataku/common" schemaLocation="../common.xsd"/>

<xs:import namespace="tataku/actions/chat" schemaLocation="./chat.xsd"/>
<xs:import namespace="tataku/actions/cursor" schemaLocation="./cursor.xsd"/>
<xs:import namespace="tataku/actions/game" schemaLocation="./game.xsd"/>
<xs:import namespace="tataku/actions/gameplay" schemaLocation="./gameplay.xsd"/>
<xs:import namespace="tataku/actions/map" schemaLocation="./map.xsd"/>
<xs:import namespace="tataku/actions/mod" schemaLocation="./mod.xsd"/>
<xs:import namespace="tataku/actions/multiplayer" schemaLocation="./multiplayer.xsd"/>
<xs:import namespace="tataku/actions/online-content" schemaLocation="./online_content.xsd"/>
<xs:import namespace="tataku/actions/slot" schemaLocation="./slot.xsd"/>
<xs:import namespace="tataku/actions/song" schemaLocation="./song.xsd"/>
<xs:import namespace="tataku/actions/ui" schemaLocation="./ui.xsd"/>

<xs:group name="action">
  <xs:choice>
      <!-- none -->
      <xs:element name="none"/>

      <!-- internal -->
      <xs:element name="internal" type="text:string"/>

      <!-- delayed -->
      <xs:element name="delayed">
        <xs:complexType>
          <xs:group ref="actions:action"/>
          <xs:attribute name="delay" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
      </xs:element>

      <!-- setMenu -->
      <xs:element name="setMenu" type="buildable-value:buildableValue">
        <xs:annotation>
          <xs:documentation>Set the current menu to the provided ID</xs:documentation>
        </xs:annotation>
      </xs:element>

      <!-- addDialog -->
      <xs:element name="addDialog" type="buildable-value:buildableValue"/>

      <xs:element name="custom" type="buildable-value:buildableValue"/>

      <xs:element name="closeDialog"/>

      <xs:element name="setValue">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:group ref="buildable-value:buildableValue-wrapped" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="key" type="text:string" use="required"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="map">
        <xs:complexType>
          <xs:group ref="map-actions:map-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="game">
        <xs:complexType>
          <xs:group ref="game-actions:game-action" minOccurs="1"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="mod">
        <xs:complexType>
          <xs:group ref="mod-actions:mod-action"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="mods">
        <xs:complexType>
          <xs:group ref="mod-actions:mod-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="song">
        <xs:complexType>
          <xs:group ref="song-actions:song-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="multiplayer">
        <xs:complexType>
          <xs:group ref="multiplayer-actions:multiplayer-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="ui">
        <xs:annotation>
          <xs:documentation>Perform a UI action</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:group ref="ui-actions:ui-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="cursor">
        <xs:complexType>
          <xs:group ref="cursor-actions:cursor-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="chat">
        <xs:complexType>
          <xs:group ref="chat-actions:chat-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="gameplay">
        <xs:complexType>
          <xs:group ref="gameplay-actions:gameplay-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="onlineContent">
        <xs:complexType>
          <xs:group ref="online-content-actions:online-content-action"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="conditional">
        <xs:complexType>
          <xs:sequence>
            <xs:choice>
              <xs:group ref="actions:action"/>
              <xs:element name="true" type="actions:action-list" />
            </xs:choice>
            <xs:element name="false" type="actions:action-list" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="cond" type="common:condition" use="required"/>
        </xs:complexType>
      </xs:element>
  </xs:choice>
</xs:group>

<xs:complexType name="action-list">
  <xs:sequence>
    <xs:group ref="actions:action" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

</xs:schema>
