<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/actions/chat"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:actions="tataku/actions"
  xmlns:text="tataku/text"
>

<xs:import namespace="tataku/text" schemaLocation="../text.xsd"/>
<xs:import namespace="tataku/actions" schemaLocation="./actions.xsd"/>


<xs:group name="chat-action">
  <xs:choice>
    <!-- send message -->
    <xs:element name="sendMessage">
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:element name="message" type="text:text"/>
          <xs:group ref="text:text-wrapped" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
    
    <!-- open channel -->
    <xs:element name="openChannel">
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:element name="password" type="text:text"/>
          <xs:group ref="text:text-wrapped" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <!-- close channel -->
    <xs:element name="closeChannel" type="text:text"/>
  </xs:choice>
</xs:group>

</xs:schema>
