<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/actions/game"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:buildable="tataku/buildable"
  xmlns:text="tataku/text"
>

<xs:import namespace="tataku/buildable" schemaLocation="../buildable.xsd"/>
<xs:import namespace="tataku/text" schemaLocation="../text.xsd"/>


<xs:group name="game-action">
  <xs:choice>
      <xs:element name="quit"/>
      <xs:element name="refreshScores"/>

      <xs:element name="viewScore" type="buildable:value"/>

      <xs:element name="notification">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element name="color" type="buildable:value" minOccurs="0"/>
            <xs:element name="duration" type="buildable:value" minOccurs="0"/>
            <xs:group ref="buildable:text" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="color" type="text:string"/>
          <xs:attribute name="duration"/>
        </xs:complexType>

        <xs:key name="notification-color">
          <xs:selector xpath="."/>
          <xs:field xpath="color|@color"/>
        </xs:key>
        <xs:key name="notification-duration">
          <xs:selector xpath="."/>
          <xs:field xpath="duration|@duration"/>
        </xs:key>
      </xs:element>

      <xs:element name="copyToClipboard" type="buildable:text"/>
  </xs:choice>
</xs:group>

</xs:schema>
