<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/actions/multiplayer"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:slot-actions="tataku/actions/slot"
  xmlns:buildable="tataku/buildable"
>

<xs:import namespace="tataku/buildable" schemaLocation="../buildable.xsd"/>
<xs:import namespace="tataku/actions/slot" schemaLocation="./slot.xsd"/>


<xs:group name="multiplayer-action">
  <xs:choice>
    <xs:element name="createLobby">
      <xs:complexType>
        <xs:all>
          <xs:element name="name" type="buildable:value" minOccurs="1"/>
          <xs:element name="password" type="buildable:value" minOccurs="0"/>
          <xs:element name="private" type="buildable:value" minOccurs="0"/>
        </xs:all>
      </xs:complexType>
    </xs:element>

    <xs:element name="joinLobby">
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:group ref="buildable:value" minOccurs="0"/>
          <xs:element name="password" type="buildable:value" minOccurs="0"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="openMapLink"/>
    <xs:element name="startMatch"/>
    <xs:element name="ready"/>
    <xs:element name="unready"/>
    <xs:element name="leave"/>
    <xs:element name="quit"/>
    <xs:element name="start"/>
    
    <xs:element name="slot" type="slot-actions:slot-action"/>

  </xs:choice>
</xs:group>

</xs:schema>
