<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/actions/slot"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:buildable-value="tataku/buildable-value"
  xmlns:slot-actions="tataku/actions/slot"
>

<xs:import namespace="tataku/buildable-value" schemaLocation="../buildable_value.xsd"/>


<xs:complexType name="slot-action" mixed="true">
  <xs:sequence>
    <xs:group ref="buildable-value:buildableValue-wrapped" minOccurs="0"/>
    <xs:choice>
      <xs:element name="showProfile"/>
      <xs:element name="move"/>
      <xs:element name="transferHost"/>
      <xs:element name="lock"/>
      <xs:element name="unlock"/>
      <xs:element name="kick"/>
    </xs:choice>
  </xs:sequence>
</xs:complexType>

</xs:schema>
