[package]
name = "tataku-game"
version = "0.5.0"
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "gameplay" ]
gameplay = [ "tokio-tungstenite", "tataku-engine/gameplay" ]
# kira_audio = ["rustfft", "uuid"]
debug_hitsounds = [ "tataku-engine/debug_hitsounds" ]
debug_perf_rating = []
debug_custom_menus = [ "tataku-interface/debug_custom_menus" ]
dynamic_gamemodes = [ "libloading", "tataku-engine/dynamic_gamemodes" ]
renderdoc = [ "dep:renderdoc" ]


storyboards = [ "tataku-engine/storyboards" ]
ui = [ "taffy", "quick-xml", "triple_buffer" ]

# removes as much graphics-side stuff as possible
graphics = [ "winit", "ui", "image", "tataku-engine/graphics", "tataku-interface", "tataku-graphics", "tataku-ui" ]

[dependencies]
tataku-audio.workspace = true
tataku-common.workspace = true
tataku-engine.workspace = true
tataku-null-audio.workspace = true
tataku-client-proc-macros.workspace = true
tataku-ui = { workspace = true, optional = true }
tataku-graphics = { workspace = true, optional = true }
tataku-interface = { workspace = true, optional = true }
tataku-client-common = { workspace = true, features = ["sql"] }

# framework stuff
tokio = { workspace = true, features = [ "full" ] }
futures-util = { workspace = true, features = [ "async-await", "sink", "std" ] }
lazy_static.workspace = true
async-trait.workspace = true
async-recursion.workspace = true
rusqlite.workspace = true

triple_buffer = { workspace = true, optional = true }
libloading = { workspace = true, optional = true }

# image stuff
image = { workspace = true, optional = true }

# windowing
winit = { workspace = true, features = ["serde"], optional = true }

# gui
taffy = { workspace = true, optional = true }
quick-xml  = { workspace = true, optional = true }


# networking
tokio-tungstenite = { workspace = true, features = [ "rustls-tls-native-roots" ], optional = true }
reqwest = { workspace = true, features = ["json"] }
rustls.workspace = true
native-tls.workspace = true
tokio-native-tls.workspace = true
rustls-graviola.workspace = true

# serde
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

# other stuff
rand.workspace = true
chrono.workspace = true
cacache.workspace = true
renderdoc = { version = "*", optional = true }

# logging
tracing.workspace = true

[build-dependencies]
tataku-common.workspace = true
