[registries.tataku]
index = "https://gitlab.ayyeve.xyz/tataku/tataku-rust-registry"


# [package.metadata.android]
# apk_name = "Tataku!"
# # runtime_libs = "path/to/libs_folder"

# # [[package.metadata.android.uses_feature]]
# # name = "android.hardware.vulkan.level"
# # required = true
# # version = 1


# [[package.metadata.android.uses_permission]]
# name = "android.permission.WRITE_EXTERNAL_STORAGE"
# max_sdk_version = 18