[package]
name = "gamemode-osu"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
gameplay = []
graphics = []
debug_sliders = []

[dependencies]
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true

tataku-common.workspace = true
tataku-engine.workspace = true
tataku-graphics.workspace = true
tataku-engine-common.workspace = true
tataku-client-proc-macros.workspace = true