[package]
name = "tataku-client-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = [ "ui" ]
ui = [ "taffy" ]
sql = [ "rusqlite" ]
debug_custom_menus = []

[dependencies]
taffy = { workspace = true, optional = true }
tataku-common.workspace = true
parking_lot.workspace = true

cgmath.workspace = true
serde.workspace = true
guillotiere.workspace = true
reqwest.workspace = true
image.workspace = true
rand.workspace = true
num-format.workspace = true
paste.workspace = true

rusqlite = { workspace = true, optional = true }
