[package]
name = "tataku-engine"
version = "0.5.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
gameplay = []
debug_hitsounds = []
debug_perf_rating = []
debug_custom_menus = []

storyboards = []
ui = [ "taffy", "triple_buffer", "simplecss" ]

# removes as much graphics-side stuff as possible
graphics = [ 
    "ui", 
    "raw-window-handle", 
    "image", 
    "tataku-graphics/graphics", 
    "tataku-client-proc-macros/graphics",
]

dynamic_gamemodes = [ "libloading" ]

[dependencies]
tataku-ui.workspace = true
tataku-input.workspace = true
tataku-common.workspace = true
tataku-graphics.workspace = true
tataku-engine-common.workspace = true
tataku-null-renderer.workspace = true
tataku-client-proc-macros.workspace = true

# framework stuff
raw-window-handle = { workspace = true, optional = true }
parking_lot.workspace = true
async-trait.workspace = true
bitflags.workspace = true
tokio.workspace = true
triple_buffer = { workspace = true, optional = true }

libloading = { workspace = true, optional = true }

# image stuff
image = { workspace = true, optional = true }

# gui
taffy = { workspace = true, optional = true }
simplecss = { workspace = true, optional = true }

# networking
ureq.workspace = true
native-tls.workspace = true
tokio-native-tls.workspace = true

# serde
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
quick-xml.workspace = true

# decoding/encoding/zip stuff
zip.workspace = true
lzma-rs.workspace = true
encoding_rs = "0.8.35"


# other stuff
rand.workspace = true
fs_extra.workspace = true
half.workspace = true


# logging
tracing.workspace = true
num-format.workspace = true
strfmt.workspace = true
