<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/elements/slider"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:buildable-value="tataku/buildable-value"
  xmlns:elements="tataku/elements"
  xmlns:actions="tataku/actions"
  xmlns:text="tataku/text"

  xmlns:slider-element="tataku/elements/slider"
>

<xs:import namespace="tataku/text" schemaLocation="../text.xsd"/>
<xs:import namespace="tataku/elements" schemaLocation="./elements.xsd"/>
<xs:import namespace="tataku/actions" schemaLocation="../actions/actions.xsd"/>
<xs:import namespace="tataku/buildable-value" schemaLocation="../buildable_value.xsd"/>


<xs:complexType name="slider-element">
  <xs:complexContent>
    <xs:extension base="elements:generic">
      <xs:all>
        <xs:element name="min" type="buildable-value:buildableValue" minOccurs="0" />
        <xs:element name="max" type="buildable-value:buildableValue" minOccurs="0"/>
        <xs:element name="step" type="buildable-value:buildableValue" minOccurs="0"/>

        <xs:element name="onInput" minOccurs="0">
          <xs:complexType>
            <xs:group ref="actions:action-type"/>
          </xs:complexType>
        </xs:element>
      </xs:all>

      <xs:attribute name="variable" type="text:string" use="required"/>
      <xs:attribute name="min" type="slider-element:slider-attribute" />
      <xs:attribute name="max" type="slider-element:slider-attribute" />
      <xs:attribute name="step" type="slider-element:slider-attribute" />
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:simpleType name="slider-attribute">
  <xs:annotation>
    <xs:documentation>Float or Variable</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:normalizedString" />
</xs:simpleType>


</xs:schema>
