<?xml version="1.0"?>

<xs:schema 
  targetNamespace="tataku/elements/switch"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:elements="tataku/elements"
  xmlns:buildable="tataku/buildable"
  xmlns:text="tataku/text"
>

<xs:import namespace="tataku/text" schemaLocation="../text.xsd"/>
<xs:import namespace="tataku/elements" schemaLocation="./elements.xsd"/>
<xs:import namespace="tataku/buildable" schemaLocation="../buildable.xsd"/>


<xs:complexType name="switch-element">
  <xs:complexContent>
    <xs:extension base="elements:generic">
      <xs:sequence>
        <!-- value -->
        <xs:element name="on" type="buildable:value" minOccurs="0" maxOccurs="1" />
         
        <!-- case -->
        <xs:element name="case" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="value" type="buildable:value" minOccurs="0" maxOccurs="1" />
              <xs:group ref="elements:element" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="cond" type="text:condition" />
            <xs:attribute name="value" type="xs:anySimpleType" />
          </xs:complexType>
        </xs:element>
        
        <!-- default -->
        <xs:element name="default" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:group ref="elements:element" minOccurs="1"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      
      <xs:attribute name="on_enum" type="text:variable-path" />
    </xs:extension>
  </xs:complexContent>
</xs:complexType>


</xs:schema>
