[package]
name = "gamemode-catch"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = [ ]
graphics = []

[dependencies]
tracing.workspace = true
async-trait.workspace = true
tataku-common.workspace = true

tataku-engine.workspace = true
tataku-engine-common.workspace = true